sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: 
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then py.test -vv MJOLNIR/init.py --cov example;
    else py.test -vv MJOLNIR/init.py;
    fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then coveralls;
    fi
