sudo: required
dist: xenial

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  

#before_install:
#- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended


#before_script: # configure a headless display to test plot generation
  #- sleep 3 # give xvfb some time to start

services:
  - xvfb

install:
  - pip install pytest>=3.6 pycodestyle python-coveralls pytest_cov>=2.5
  - pip install .
#  - pip install -r requirements.txt

script: 
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then py.test MJOLNIR/ -vv --cov MJOLNIR; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then py.test MJOLNIR/ -vv --ignore=MJOLNIR/CommandLineScripts/MJOLNIRHistory.py --ignore=MJOLNIR/CommandLineScripts/MJOLNIRCalibrationInspector.py --ignore=MJOLNIR/CommandLineScripts/MJOLNIR3DView.py --ignore=MJOLNIR/CommandLineScripts/MJOLNIRConvert.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 3.6 ]] and [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then py.test MJOLNIR/ -vv ; fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]];
    then coveralls;
    fi

notifications:
  email: false
