sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"


install:
  - pip install -r requirements.txt

script: 
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]];
    then py.test MJOLNIR/ -vv --cov MJOLNIR;
    else py.test MJOLNIR/ -vv;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]];
    then coveralls;
    fi

notifications:
  email: false
